print("Zul Hilmi")
print("XI.RPL-3")
print('-----------')
print("Hilmi")
print("XI.RPL-3")
print('-----------')
print("Irene")
print("XI.RPL-3")
print('-----------')
print("Zul Hilmi")
print("XI.RPL-3")
print('-----------')
print("Hilmi")
print("XI.RPL-3")
print('-----------')
print("Irene")
print("XI.RPL-3")
print('-----------')