x = input('X: ')
y = input('Y: ')

tambah = int(x) + int(y)
bagi = int(x) / int(y)
kali = int(x) * int(y)
kurang = int(x) - int(y)
pangkat = int(x) ** int(y)
pembulatan = int(x) // int(y)
mod = int(x) % int(y)

print(tambah)
print(bagi)
print(kali)
print(kurang)
print(pangkat)
print(pembulatan)
print(mod)
